name: robotlinker-demo
version: 1.0
summary: RobotLinker-Core on Edge Gateway Demo Package
description: Contains talker/listener ROS packages, AWS, UR10 Driver and ROS-Bridge packages.
grade: stable
confinement: strict

apps:
  launch-project:
    command: roslaunch ur_modern_driver robotlinker_demo.launch
    plugs: [network-bind]

parts:
  demo-project:
    plugin: catkin
    source: .
    catkin-packages:
      - talker
      - listener
      - aws_gateway
      - rosbridge_suite
      - ur_modern_driver
      - ur_msgs
    include-roscore: true
