name: robotlinker-demo
version: 1.0
summary: RobotLinker-Core on Edge Gateway Demo Package
description: Contains talker/listener ROS packages, AWS, UR10 Driver and ROS-Bridge packages.
grade: stable
confinement: strict

apps:
  launch-robot:
    command: roslaunch ur_modern_driver robotlinker_demo.launch
    plugs: [network, network-bind]
    daemon: simple
 
  launch-aws:
    command:  rosrun aws_gateway AWS_ROS_pubsub -e a1zzeyxtagz2r4.iot.ap-southeast-1.amazonaws.com -r ~/robotlinker_ws/src/aws_gateway/src/keys/root-CA.crt -c ~/robotlinker_ws/src/aws_gateway/src/keys/8e17a6779d-certificate.pem.crt -k ~/robotlinker_ws/src/aws_gateway/src/keys/8e17a6779d-private.pem.key
    plugs: [network, network-bind]
    daemon: simple


parts:
  demo-project:
    plugin: catkin
    source: .
    catkin-packages:
      - talker
      - listener
      - aws_gateway
      - rosbridge_suite
      - ur_modern_driver
      - ur_msgs
    include-roscore: true
